### ISSUE TITLE
Clean up notebooks

### ISSUE THREAD

**Issue by lzachmann** [csp-inc/fluvius#34]
Need to go through the notebooks folder and remove / archive anything that is not 'current' or useful. Ideally we might have just one or two notebooks that show how fluvius works.

**Comment by tonychang-cspinc** [comment]
I moved the two demo notebooks that have extensive tutorial language within on using tabular data on Planetary Computer and accessing STAC catalog

**Comment by lzachmann** [comment]
Looks great!
